### Regression with ANN

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [2]:
import seaborn as sns

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [4]:
from sklearn import datasets as skd

In [5]:
diabetes = skd.load_diabetes()

In [6]:
print(diabetes['DESCR'])

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, T-Cells (a type of white blood cells)
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, thyroid stimulating hormone
      - s5      ltg, lamotrigine
      - s6      glu, blood sugar level

Note: Each of these 10 feature va

In [7]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [8]:
diabetes.get('feature_names')

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [9]:
diabetes.get('data')[:,-1]

array([-0.01764613, -0.09220405, -0.02593034, -0.00936191, -0.04664087,
       -0.09634616, -0.03835666,  0.00306441,  0.01134862, -0.01350402,
       -0.03421455, -0.05906719, -0.04249877, -0.01350402, -0.07563562,
       -0.04249877,  0.02791705, -0.0010777 , -0.01764613, -0.05492509,
        0.01549073, -0.01764613, -0.01350402,  0.13561183, -0.05492509,
       -0.03421455, -0.0052198 ,  0.04034337, -0.05492509,  0.05276969,
       -0.00936191, -0.04249877,  0.02791705,  0.00306441, -0.06735141,
        0.01963284, -0.02593034, -0.0052198 ,  0.02377494,  0.00306441,
        0.09419076, -0.00936191, -0.03421455,  0.07348023, -0.01764613,
       -0.05078298, -0.08806194, -0.08391984, -0.02178823, -0.01350402,
        0.00720652, -0.02178823, -0.01350402,  0.04862759,  0.00720652,
        0.00720652, -0.01764613, -0.06735141, -0.05078298,  0.01963284,
       -0.03421455,  0.01963284, -0.02593034, -0.07149352,  0.01134862,
        0.01549073,  0.01963284,  0.00306441,  0.00306441,  0.01

In [10]:
diabetes.get('target')

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [11]:
from keras.datasets import boston_housing as bh

In [12]:
(xtrain,ytrain),(xtest,ytest) = bh.load_data()

In [13]:
xtrain

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [14]:
xtrain[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [15]:
ytrain[0]

15.2

In [16]:
from keras.layers import Dense
from keras.models import Sequential

In [17]:
from keras.callbacks import EarlyStopping

In [18]:
es = EarlyStopping(monitor='loss',patience=20)

In [19]:
model = Sequential()
model.add(Dense(activation='relu',input_shape=(13,), units=65))
model.add(Dense(activation='relu', units=65))
model.add(Dense(activation='relu', units=65))
model.add(Dense(activation='relu', units=65))
model.add(Dense(activation='relu', units=65))
model.add(Dense(activation = 'relu', units = 1))
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae','accuracy'])

In [20]:
h = model.fit(xtrain,ytrain,epochs=3000,callbacks=[es])

Epoch 1/3000
13/13 [==============================] - 13s 1ms/step - loss: 278.2737 - mae: 12.7894 - accuracy: 0.0000e+00
Epoch 2/3000
13/13 [==============================] - 0s 1ms/step - loss: 89.1978 - mae: 6.8284 - accuracy: 0.0000e+00
Epoch 3/3000
13/13 [==============================] - 0s 2ms/step - loss: 60.4743 - mae: 5.8248 - accuracy: 0.0000e+00
Epoch 4/3000
13/13 [==============================] - 0s 2ms/step - loss: 64.6908 - mae: 5.5199 - accuracy: 0.0000e+00
Epoch 5/3000
13/13 [==============================] - 0s 2ms/step - loss: 67.5745 - mae: 5.8331 - accuracy: 0.0000e+00
Epoch 6/3000
13/13 [==============================] - 0s 2ms/step - loss: 57.1961 - mae: 5.3811 - accuracy: 0.0000e+00
Epoch 7/3000
13/13 [==============================] - 0s 1ms/step - loss: 67.3971 - mae: 5.8644 - accuracy: 0.0000e+00
Epoch 8/3000
13/13 [==============================] - 0s 1ms/step - loss: 61.0376 - mae: 5.6695 - accuracy: 0.0000e+00
Epoch 9/3000
13/13 [=========================

In [21]:
h.history

{'loss': [162.89915466308594,
  75.59446716308594,
  69.8592529296875,
  72.63516235351562,
  67.39225769042969,
  65.66104125976562,
  72.15730285644531,
  64.5972671508789,
  64.87655639648438,
  63.67903518676758,
  57.023948669433594,
  67.45817565917969,
  58.01059341430664,
  60.81245040893555,
  59.12289047241211,
  59.46052551269531,
  58.60152053833008,
  55.753746032714844,
  51.811580657958984,
  52.4247932434082,
  52.79237747192383,
  60.239402770996094,
  52.403934478759766,
  57.309852600097656,
  47.5506706237793,
  46.880096435546875,
  51.33988571166992,
  51.63383102416992,
  49.101707458496094,
  43.6885986328125,
  52.78704071044922,
  46.742820739746094,
  48.659812927246094,
  37.609561920166016,
  45.094261169433594,
  39.15292739868164,
  46.03564453125,
  39.73222732543945,
  43.937721252441406,
  41.925811767578125,
  39.04243087768555,
  42.24740219116211,
  30.159875869750977,
  40.26226043701172,
  39.16217803955078,
  38.650596618652344,
  36.224845886230

### Saving Model

In [23]:
model.save('bhmodel')

INFO:tensorflow:Assets written to: bhmodel\assets


In [24]:
import keras

In [25]:
m = keras.models.load_model('bhmodel')

In [26]:
m.predict(xtest[0:2,:])

array([[ 9.986994],
       [16.820913]], dtype=float32)

In [27]:
ytest[:2]

array([ 7.2, 18.8])

# RECURRENT NEURAL NETWORK

In [28]:
stocks = pd.read_csv('stock_data.csv')

In [29]:
stocks.head()

Date     Open     High      Low    Close    Volume  OpenInt Stock
0  1984-09-07  0.42388  0.42902  0.41874  0.42388  23220030        0  AAPL
1  1984-09-10  0.42388  0.42516  0.41366  0.42134  18022532        0  AAPL
2  1984-09-11  0.42516  0.43668  0.42516  0.42902  42498199        0  AAPL
3  1984-09-12  0.42902  0.43157  0.41618  0.41618  37125801        0  AAPL
4  1984-09-13  0.43927  0.44052  0.43927  0.43927  57822062        0  AAPL

In [30]:
stocks['Stock'].value_counts()

AAPL    8364
MSFT    7983
TSLA    1858
FB      1381
Name: Stock, dtype: int64

In [31]:
msft = stocks[['Date','Open']][stocks['Stock']=='MSFT']

In [32]:
msft

Date      Open
10222  1986-03-13   0.06720
10223  1986-03-14   0.07533
10224  1986-03-17   0.07533
10225  1986-03-18   0.07533
10226  1986-03-19   0.07533
...           ...       ...
18200  2017-11-06  84.20000
18201  2017-11-07  84.77000
18202  2017-11-08  84.14000
18203  2017-11-09  84.11000
18204  2017-11-10  83.79000

[7983 rows x 2 columns]

In [33]:
7983/50

159.66

In [34]:
x=[]
y=[]
for i in range(100,len(msft)):
    x.append(msft['Open'].values[i-100:i])
    y.append(msft['Open'].values[i])
x=np.array(x)
y=np.array(y)

In [35]:
x.shape

(7883, 100)

In [36]:
x= np.reshape(x,(x.shape[0],x.shape[1],1))

In [37]:
x.shape

(7883, 100, 1)

In [38]:
len(x)

7883

In [39]:
y

array([7.533e-02, 7.533e-02, 7.533e-02, ..., 8.414e+01, 8.411e+01,
       8.379e+01])

In [40]:
from keras.layers import LSTM

In [41]:
model = Sequential()
model.add(LSTM(units=200,return_sequences=True,input_shape=(100,1)))
model.add(LSTM(units=200,return_sequences=True))
model.add(LSTM(units=200,return_sequences=True))
model.add(LSTM(units=200,return_sequences=True))
model.add(LSTM(units=200,return_sequences=True))
model.add(LSTM(units=200))
model.add(Dense(units=1))
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae','accuracy'])

In [42]:
model.fit(x,y,epochs=10,batch_size=50)

Epoch 1/10
158/158 [==============================] - 211s 1s/step - loss: 194.9564 - mae: 8.1702 - accuracy: 0.0000e+00
Epoch 2/10
158/158 [==============================] - 201s 1s/step - loss: 46.3502 - mae: 3.6898 - accuracy: 0.0000e+00
Epoch 3/10
158/158 [==============================] - 225s 1s/step - loss: 23.0579 - mae: 2.6322 - accuracy: 0.0000e+00
Epoch 4/10
158/158 [==============================] - 227s 1s/step - loss: 10.9164 - mae: 1.8031 - accuracy: 0.0000e+00
Epoch 5/10
158/158 [==============================] - 233s 1s/step - loss: 6.4550 - mae: 1.4461 - accuracy: 0.0000e+00
Epoch 6/10
158/158 [==============================] - 222s 1s/step - loss: 5.9740 - mae: 1.3395 - accuracy: 0.0000e+00
Epoch 7/10
158/158 [==============================] - 224s 1s/step - loss: 5.9303 - mae: 1.4992 - accuracy: 0.0000e+00
Epoch 8/10
158/158 [==============================] - 233s 1s/step - loss: 4.9216 - mae: 1.2363 - accuracy: 0.0000e+00
Epoch 9/10
158/158 [=======================